In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 

In [2]:
a=[2,4,6]
b=[1,3,5]

In [3]:
dt=np.dot(a,b) 
dt 

44

# Question 2

In [4]:
x=[[1,2],[3,4],[5,6]]
y=[0.5,1.5]

In [5]:
result=np.dot(x,y)
result 

array([ 3.5,  7.5, 11.5])

In [6]:
result.shape

(3,)

# Question 3

In [8]:
x=[[1,2,3],[4,5,6]]
y=[0.2,-0.3]

In [10]:
x=np.matrix(x)
x 

matrix([[1, 2, 3],
        [4, 5, 6]])

In [14]:
x_trans=np.transpose(x)
x_trans

matrix([[1, 4],
        [2, 5],
        [3, 6]])

In [15]:
result=np.dot(x_trans,y)
result 

matrix([[-1. , -1.1, -1.2]])

# Question 3

In [16]:
x=[[2,4],[6,8]]
y=[[5],[10]]
w=[[0.5],[1.0]]

In [17]:
y_pred=np.dot(x,w)
y_pred 

array([[ 5.],
       [11.]])

In [20]:
gradient=-2*np.dot(np.transpose(x),(y-y_pred))
gradient

array([[12.],
       [16.]])

# Question 4 

In [27]:
w=np.array([[1],[2]])
lr=0.01
w_der=np.array([[0.5],[-1.5]])

In [28]:
w=w-(lr*w_der)
w

array([[0.995],
       [2.015]])

# Question 5 

# Gradient for Sigmoid function

In [48]:
z=np.array([[1.0],[2.0],[3.0]])
sig=1/(1+np.exp(-z))
sigmoid_der=sig*(1-sig)
sigmoid_der

array([[0.19661193],
       [0.10499359],
       [0.04517666]])

# Using Stochastic Gradient Descent Update 