In [1]:
import pandas as pd 
import numpy as np 


array1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

new_array=array1.reshape(-1,1)
new_array

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [15]:
array2 = np.arange(1, 25)
array2
# now reshaping array2

new_array2=array2.reshape(2,3,4)
new_array2

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [17]:
import pprint as pp
#Using prety print too display it in suitable format
p=pp.pprint(array2)
p

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])


In [19]:
array3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])  

new_array3=array3.flatten()
new_array3


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [24]:
array4 = np.arange(1, 21)  

new_array4=array4.reshape(-1,2)
new_array4


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])