In [4]:
import random 
import pandas as pd 
import numpy as np

In [5]:
 
p=np.random.randint(0,100,size=(4,4))
print(p)
p.shape



[[42 52 47 66]
 [50 56  2 40]
 [ 0 62 92 15]
 [64 93 90 57]]


(4, 4)

In [6]:
type(p)



numpy.ndarray

In [7]:
pm=np.matrix(p)
print(pm)
pm.shape



[[42 52 47 66]
 [50 56  2 40]
 [ 0 62 92 15]
 [64 93 90 57]]


(4, 4)

In [8]:
type(pm)



numpy.matrix

# Appling Ravel Function 


In [9]:

p_ravel=np.ravel(p) 
print(p_ravel)
p_ravel.shape


[42 52 47 66 50 56  2 40  0 62 92 15 64 93 90 57]


(16,)

In [10]:

type(p_ravel)


numpy.ndarray

# Applying flatten Function 

In [11]:
p_flatten=p.flatten()
print(p_flatten)
p_flatten.shape

[42 52 47 66 50 56  2 40  0 62 92 15 64 93 90 57]


(16,)

## applying Change on the ravel function applied variable 


In [12]:
p_ravel[0]=-1
p_ravel

print(p)

[[-1 52 47 66]
 [50 56  2 40]
 [ 0 62 92 15]
 [64 93 90 57]]


## Aplying Change on the flatten function Applied variable 


In [13]:
p_flatten[1]=-1
print(p_flatten)

print(p)

[42 -1 47 66 50 56  2 40  0 62 92 15 64 93 90 57]
[[-1 52 47 66]
 [50 56  2 40]
 [ 0 62 92 15]
 [64 93 90 57]]
